export interface Product {
    id: string;
    name: string;
    description: string;
    price: number;
    discountPrice?: number;
    category: 'Laptops' | 'Phones' | 'Accessories' | 'Perfumes';
    subcategory: string;
    brand: string;
    rating: number;
    reviews: number;
    stock: number; // For progress bars
    recentSales: string; // e.g., "50+ bought recently"
    image: any;
    images: any[];
    specs: { [key: string]: string };
}

export const PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'APPLE MACBOOK PRO 16 TOUCHBAR',
        description: 'The most powerful MacBook Pro ever. Features the new M3 Max chip for extreme performance.',
        price: 5937.00,
        discountPrice: 6500.00,
        category: 'Laptops',
        subcategory: 'Professional',
        brand: 'Apple',
        rating: 4.8,
        reviews: 245,
        stock: 5,
        recentSales: '12 bought in last hour',
        image: require('../assets/MacBook.webp'),
        images: [
            require('../assets/Mac1.webp'),
            require('../assets/Mac2.webp'),
        ],
        specs: {
            Display: '16-inch Liquid Retina XDR',
            Processor: 'APPLE MACBOOK PRO 16 TOUCHBAR 32GB RAM 512GB SSD 8 CORE 5.0GHz i9 - TAHOE',
            RAM: '36GB',
            Storage: '1TB SSD',
        },
    },
    {
        id: '2',
        name: 'Apple iPhone 15 Pro Max 6.7',
        description: 'Apple iPhone 15 Pro Max 6.7" Unlocked 512GB - (Blue Titanium) A2849 w/Warranty.',
        price: 8900.00,
        category: 'Phones',
        subcategory: 'Flagship',
        brand: 'Apple',
        rating: 4.9,
        reviews: 890,
        stock: 120,
        recentSales: '1k+ sold',
        image: require('../assets/Iphone 15 Pro mMax.webp'),
        images: [
            require('../assets/iPhone 15.webp'),
        ],
        specs: {
            Display: '6.7-inch Super Retina XDR',
            Processor: 'A17 Pro',
            Camera: '48MP Main | Ultra Wide | Telephoto',
            Battery: 'Up to 29 hours video playback',
        },
    },
    {
        id: '3',
        name: 'Sony WH-1000XM5',
        description: 'ORIGINAL Sony WH-1000XM5 Wireless Noise Canceling Headphones - Black GA.',
        price: 398.00,
        discountPrice: 250.00,
        category: 'Accessories',
        subcategory: 'Headphones',
        brand: 'Sony',
        rating: 4.7,
        reviews: 120,
        stock: 8,
        recentSales: 'Almost sold out',
        image: require('../assets/Sony WH-1000XM5.webp'),
        images: [
            require('../assets/Sony WH-1000XM5.webp'),
        ],
        specs: {
            Type: 'Over-ear',
            BatteryLife: '30 hours',
            Features: 'Noise Canceling, Multipoint',
        },
    },
    {
        id: '4',
        name: 'Dior Sauvage Elixir',
        description: 'Dior Sauvage Men\'s 3.4 fl oz Parfum Spray.',
        price: 100.00,
        discountPrice: 85.00,
        category: 'Perfumes',
        subcategory: 'Mens',
        brand: 'Dior',
        rating: 4.9,
        reviews: 56,
        stock: 45,
        recentSales: 'High demand',
        image: require('../assets/Dior Sauvage Elixir.webp'),
        images: [
            require('../assets/Dior Sauvage Elixir.webp'),
        ],
        specs: {
            Size: '60ml',
            Type: 'Parfum',
            Notes: 'Grapefruit, Spices, Organic AOP Lavender, Woods',
        },
    },
    {
        id: '5',
        name: 'Dell XPS 15',
        description: 'Dell XPS 15 9530 – 15.6" FHD+ – i9-13700H – 16GB RAM–Arc A370M–512GB SSD –Silver.',
        price: 9500.00,
        category: 'Laptops',
        subcategory: 'Business',
        brand: 'Dell',
        rating: 4.6,
        reviews: 88,
        stock: 2,
        recentSales: 'Last 2 left!',
        image: require('../assets/Dell.webp'),
        images: [
            require('../assets/Dell2.webp'),
        ],
        specs: {
            Display: '15.6" OLED 3.5K',
            Processor: 'Intel Core i9',
            RAM: '16GB',
            Storage: '512GB SSD',
        },
    },
    {
        id: '6',
        name: 'Samsung Galaxy S24 Ultra',
        description: 'open box Samsung Galaxy S24 Ultra 512GB S-928U1 Titanium gray factory unlockedOpens in a new window or tab',
        price: 8800.00,
        category: 'Phones',
        subcategory: 'Flagship',
        brand: 'Samsung',
        rating: 4.8,
        reviews: 312,
        stock: 200,
        recentSales: 'Popular',
        image: require('../assets/Samsung Galaxy S24 Ultra.webp'),
        images: [
            require('../assets/Samsung Galaxy S24 Ultra.webp'),
        ],
        specs: {
            Display: '6.8" QHD+',
            Processor: 'Snapdragon 8 Gen 3',
            Camera: '200MP Main',
            Battery: '5000mAh',
        },
    },
    // Additional Laptops
    {
        id: '7',
        name: 'Lenovo ThinkPad X1 Carbon',
        description: 'Premium business laptop with exceptional performance and portability.',
        price: 7200.00,
        discountPrice: 6800.00,
        category: 'Laptops',
        subcategory: 'Business',
        brand: 'Lenovo',
        rating: 4.7,
        reviews: 156,
        stock: 15,
        recentSales: '8 sold this week',
        image: require('../assets/Dell.webp'),
        images: [require('../assets/Dell2.webp')],
        specs: {
            Display: '14" OLED',
            Processor: 'Intel Core i7-13th Gen',
            RAM: '16GB',
            Storage: '512GB SSD',
        },
    },
    {
        id: '8',
        name: 'ASUS VivoBook 15',
        description: 'Affordable yet powerful laptop for everyday computing tasks.',
        price: 4500.00,
        category: 'Laptops',
        subcategory: 'Budget',
        brand: 'ASUS',
        rating: 4.5,
        reviews: 234,
        stock: 30,
        recentSales: '45+ sold',
        image: require('../assets/Dell.webp'),
        images: [require('../assets/Dell2.webp')],
        specs: {
            Display: '15.6" FHD',
            Processor: 'AMD Ryzen 5',
            RAM: '8GB',
            Storage: '256GB SSD',
        },
    },
    {
        id: '9',
        name: 'HP Pavilion 14',
        description: 'Compact and stylish laptop perfect for students and professionals.',
        price: 3800.00,
        discountPrice: 3200.00,
        category: 'Laptops',
        subcategory: 'Budget',
        brand: 'HP',
        rating: 4.3,
        reviews: 189,
        stock: 50,
        recentSales: '60+ bought',
        image: require('../assets/Dell.webp'),
        images: [require('../assets/Dell2.webp')],
        specs: {
            Display: '14" FHD',
            Processor: 'Intel Core i5',
            RAM: '8GB',
            Storage: '512GB SSD',
        },
    },
    {
        id: '10',
        name: 'Toshiba Satellite Pro',
        description: 'Reliable workhorse laptop for business professionals.',
        price: 5500.00,
        category: 'Laptops',
        subcategory: 'Business',
        brand: 'Toshiba',
        rating: 4.4,
        reviews: 112,
        stock: 20,
        recentSales: '12 sold recently',
        image: require('../assets/Dell.webp'),
        images: [require('../assets/Dell2.webp')],
        specs: {
            Display: '15.6" FHD',
            Processor: 'Intel Core i7',
            RAM: '16GB',
            Storage: '512GB SSD',
        },
    },
    // Additional Phones
    {
        id: '11',
        name: 'Google Pixel 8 Pro',
        description: 'Google Pixel 8 Pro with advanced AI features and amazing camera.',
        price: 7500.00,
        category: 'Phones',
        subcategory: 'Flagship',
        brand: 'Google',
        rating: 4.7,
        reviews: 421,
        stock: 85,
        recentSales: '200+ sold',
        image: require('../assets/Iphone 15 Pro mMax.webp'),
        images: [require('../assets/iPhone 15.webp')],
        specs: {
            Display: '6.7" OLED',
            Processor: 'Google Tensor G3',
            Camera: '50MP Main + AI Magic Eraser',
            Battery: '5000mAh',
        },
    },
    {
        id: '12',
        name: 'OnePlus 12',
        description: 'Fast and smooth performance with premium design.',
        price: 6500.00,
        discountPrice: 5999.00,
        category: 'Phones',
        subcategory: 'Mid-Range',
        brand: 'OnePlus',
        rating: 4.6,
        reviews: 287,
        stock: 120,
        recentSales: '150+ bought',
        image: require('../assets/Iphone 15 Pro mMax.webp'),
        images: [require('../assets/iPhone 15.webp')],
        specs: {
            Display: '6.7" AMOLED',
            Processor: 'Snapdragon 8 Gen 3',
            Camera: '50MP Main',
            Battery: '5400mAh',
        },
    },
    {
        id: '13',
        name: 'Xiaomi 14 Ultra',
        description: 'Excellent value flagship phone with professional camera system.',
        price: 5800.00,
        category: 'Phones',
        subcategory: 'Mid-Range',
        brand: 'Xiaomi',
        rating: 4.5,
        reviews: 356,
        stock: 95,
        recentSales: '180+ bought',
        image: require('../assets/Iphone 15 Pro mMax.webp'),
        images: [require('../assets/iPhone 15.webp')],
        specs: {
            Display: '6.73" OLED',
            Processor: 'Snapdragon 8 Gen 3',
            Camera: '50MP with Leica Optics',
            Battery: '5800mAh',
        },
    },
    {
        id: '14',
        name: 'Samsung Galaxy A54',
        description: 'Mid-range Samsung with solid performance and great display.',
        price: 3500.00,
        category: 'Phones',
        subcategory: 'Budget',
        brand: 'Samsung',
        rating: 4.4,
        reviews: 512,
        stock: 200,
        recentSales: '400+ sold',
        image: require('../assets/Iphone 15 Pro mMax.webp'),
        images: [require('../assets/iPhone 15.webp')],
        specs: {
            Display: '6.4" OLED',
            Processor: 'Exynos 1280',
            Camera: '50MP Main',
            Battery: '5000mAh',
        },
    },
    // Additional Accessories
    {
        id: '15',
        name: 'Apple AirPods Pro 2',
        description: 'Premium wireless earbuds with active noise cancellation.',
        price: 249.00,
        category: 'Accessories',
        subcategory: 'Earbuds',
        brand: 'Apple',
        rating: 4.8,
        reviews: 890,
        stock: 150,
        recentSales: '500+ sold',
        image: require('../assets/Sony WH-1000XM5.webp'),
        images: [require('../assets/Sony WH-1000XM5.webp')],
        specs: {
            Type: 'True Wireless',
            BatteryLife: '6 hours (30 with case)',
            Features: 'ANC, Transparency Mode',
            Charging: 'USB-C',
        },
    },
    {
        id: '16',
        name: 'Samsung Galaxy Buds 2 Pro',
        description: 'Great sounding earbuds with excellent noise cancellation.',
        price: 199.00,
        discountPrice: 149.00,
        category: 'Accessories',
        subcategory: 'Earbuds',
        brand: 'Samsung',
        rating: 4.6,
        reviews: 654,
        stock: 120,
        recentSales: '300+ sold',
        image: require('../assets/Sony WH-1000XM5.webp'),
        images: [require('../assets/Sony WH-1000XM5.webp')],
        specs: {
            Type: 'True Wireless',
            BatteryLife: '5 hours (18 with case)',
            Features: 'ANC, 360 Audio',
            Charging: 'USB-C',
        },
    },
    {
        id: '17',
        name: 'JBL Flip 6',
        description: 'Portable Bluetooth speaker with powerful sound.',
        price: 129.00,
        category: 'Accessories',
        subcategory: 'Speakers',
        brand: 'JBL',
        rating: 4.5,
        reviews: 432,
        stock: 80,
        recentSales: '200+ sold',
        image: require('../assets/Sony WH-1000XM5.webp'),
        images: [require('../assets/Sony WH-1000XM5.webp')],
        specs: {
            Type: 'Portable Speaker',
            BatteryLife: '12 hours',
            Features: 'Waterproof, Deep Bass',
            Charging: 'USB-C',
        },
    },
    {
        id: '18',
        name: 'Beats Studio Pro',
        description: 'Premium over-ear headphones with superior sound quality.',
        price: 399.00,
        category: 'Accessories',
        subcategory: 'Headphones',
        brand: 'Beats',
        rating: 4.7,
        reviews: 512,
        stock: 60,
        recentSales: '150+ sold',
        image: require('../assets/Sony WH-1000XM5.webp'),
        images: [require('../assets/Sony WH-1000XM5.webp')],
        specs: {
            Type: 'Over-ear',
            BatteryLife: '40 hours',
            Features: 'ANC, Spatial Audio',
            Charging: 'USB-C',
        },
    },
    // Additional Perfumes
    {
        id: '19',
        name: 'Creed Aventus',
        description: 'Luxury mens fragrance with sophisticated notes.',
        price: 280.00,
        category: 'Perfumes',
        subcategory: 'Mens',
        brand: 'Creed',
        rating: 4.9,
        reviews: 234,
        stock: 25,
        recentSales: '50+ sold',
        image: require('../assets/Dior Sauvage Elixir.webp'),
        images: [require('../assets/Dior Sauvage Elixir.webp')],
        specs: {
            Size: '120ml',
            Type: 'Eau de Parfum',
            Notes: 'Pineapple, Birch, Ambroxan',
        },
    },
    {
        id: '20',
        name: 'Chanel No. 5',
        description: 'Iconic womens fragrance, timeless classic.',
        price: 220.00,
        category: 'Perfumes',
        subcategory: 'Womens',
        brand: 'Chanel',
        rating: 4.8,
        reviews: 567,
        stock: 40,
        recentSales: '120+ sold',
        image: require('../assets/Dior Sauvage Elixir.webp'),
        images: [require('../assets/Dior Sauvage Elixir.webp')],
        specs: {
            Size: '100ml',
            Type: 'Eau de Parfum',
            Notes: 'Neroli, Jasmine, Sandalwood',
        },
    },
    {
        id: '21',
        name: 'Guerlain La Vie Est Belle',
        description: 'Sweet and sensual womens fragrance.',
        price: 185.00,
        discountPrice: 150.00,
        category: 'Perfumes',
        subcategory: 'Womens',
        brand: 'Guerlain',
        rating: 4.7,
        reviews: 389,
        stock: 55,
        recentSales: '180+ sold',
        image: require('../assets/Dior Sauvage Elixir.webp'),
        images: [require('../assets/Dior Sauvage Elixir.webp')],
        specs: {
            Size: '100ml',
            Type: 'Eau de Parfum',
            Notes: 'Iris, Patchouli, Vanilla',
        },
    },
    {
        id: '22',
        name: 'Tom Ford Black Orchid',
        description: 'Luxurious dark floral fragrance.',
        price: 210.00,
        category: 'Perfumes',
        subcategory: 'Unisex',
        brand: 'Tom Ford',
        rating: 4.8,
        reviews: 423,
        stock: 30,
        recentSales: '90+ sold',
        image: require('../assets/Dior Sauvage Elixir.webp'),
        images: [require('../assets/Dior Sauvage Elixir.webp')],
        specs: {
            Size: '100ml',
            Type: 'Eau de Parfum',
            Notes: 'Black Orchid, Rum, Amber',
        },
    },
];
